{% set name = "opentelemetry-instrumentation-redis" %}
{% set version = "0.64b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: c37e194c1e8ff59944d5c2f18014ee18f244a103958b1f2482099525ae9099f9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-semantic-conventions =={{ version }}
    - wrapt >=1.12.1
  run_constrained:
    - redis-py >=2.6

# Unable to run tests, fakeredis is not in the main channel.
# E   ModuleNotFoundError: No module named 'fakeredis'
test:
  imports:
    - opentelemetry.instrumentation.redis
  commands:
    - pip check
  requires:
    - pip
    - redis-py >=2.6

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  summary: OpenTelemetry Redis instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing requests made by the Redis library.
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  doc_url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/redis/redis.html

extra:
  recipe-maintainers:
    - mariusvniekerk
  skip-lints:
    - invalid_url
    - documentation_specifies_language
