{% set name = "opentelemetry-instrumentation-redis" %}
{% set version = "0.31b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-redis-{{ version }}.tar.gz
  sha256: 2cbcbadef7256fc7f4355bd8551c72d1f6c8c9b05c721aac3dbdd37515127f09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.31b0
    - opentelemetry-semantic-conventions ==0.31b0
    - python >=3.6
    - wrapt >=1.12.1
    # - redis-py >=2.6
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.29b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.30b0
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.30b1
    # - opentelemetry-sdk ~=1.3
    # - redis-py >=2.6
    # - opentelemetry-test-utils ==0.31b0
    # - opentelemetry-sdk ~=1.3

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  summary: OpenTelemetry Redis instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
