{% set name = "opentelemetry-instrumentation-redis" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 6271f10a9ee0572f1c67f630b098326a4fe02b898c46a173942766c00307914a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-semantic-conventions =={{ version }}
    - wrapt >=1.12.1
  run_constrained:
    - redis-py >=2.6

# Unable to run tests, fakeredis is not in the main channel.
# E   ModuleNotFoundError: No module named 'fakeredis'
test:
  imports:
    - opentelemetry.instrumentation.redis
  commands:
    - pip check
  requires:
    - pip
    - redis-py >=2.6

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  summary: OpenTelemetry Redis instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing requests made by the Redis library.
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  doc_url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/redis/redis.html

extra:
  recipe-maintainers:
    - mariusvniekerk
  skip-lints:
    - invalid_url
    - documentation_specifies_language
